public class HelloUser{
    public static void userName(String name){
       System.debug('Hello : '+name);
        
    }
    public static void div(Integer a,Integer b){
      Integer div = a/b;
        system.debug('Division : '+ div );
        
    }
    public static string name(){
        system.debug('Ravendra');
        return 'Ravendra';
    }
    public static Integer i(){
        system.debug('Ravendra');
        return 10;
    }
    public static List<string> Str(){
       List<String> nameList=new List<String>();
        return nameList;
    }
    public static List<Integer> integ(){
       List<Integer> nameList=new List<Integer>();
        return nameList;
    }

}